# Generated by Django 4.2.4 on 2023-08-25 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Juicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruc', models.CharField(max_length=25)),
                ('auto_apertura', models.CharField(max_length=200, null=True)),
                ('fecha_juicio_oral', models.DateField(null=True)),
                ('fiscal', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Victima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('rut', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=200)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=50)),
                ('bool_esta_notificada', models.BooleanField(default=False)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('edad', models.IntegerField(null=True)),
                ('bool_pauta_lista', models.BooleanField(default=False)),
                ('link_pauta_necesidades', models.URLField(null=True)),
                ('id_juicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='victimas', to='trial.juicio')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Testigo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('rut', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=200)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=50)),
                ('bool_esta_notificada', models.BooleanField(default=False)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('edad', models.IntegerField(null=True)),
                ('bool_pauta_lista', models.BooleanField(default=False)),
                ('link_pauta_necesidades', models.URLField(null=True)),
                ('id_juicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testigos', to='trial.juicio')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Responsable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('es', 'Equipo Especial Juicios'), ('ur', 'Equipo URAVIT'), ('fi', 'Equipo Fiscal'), ('ug', 'Equipo UGI')], max_length=2)),
                ('nombre', models.CharField(max_length=30)),
                ('id_juicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsables', to='trial.juicio')),
            ],
        ),
        migrations.CreateModel(
            name='Perito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('rut', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=200)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=50)),
                ('bool_esta_notificada', models.BooleanField(default=False)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('institucion', models.CharField(max_length=30)),
                ('id_juicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peritos', to='trial.juicio')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PautaNecesidadesVictima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('traslado', models.TextField()),
                ('alojamiento', models.TextField()),
                ('id_victima', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pauta_necesidades', to='trial.victima')),
            ],
        ),
        migrations.CreateModel(
            name='PautaNecesidadesTestigo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('traslado', models.TextField()),
                ('alojamiento', models.TextField()),
                ('id_testigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pauta_necesidades', to='trial.testigo')),
            ],
        ),
    ]
