# Generated by Django 4.2.4 on 2023-09-28 18:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Juicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruc', models.CharField(max_length=25)),
                ('auto_apertura', models.CharField(max_length=200, null=True)),
                ('fecha_juicio_oral', models.DateTimeField()),
                ('fiscal', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Victima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('rut', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=200)),
                ('correo', models.EmailField(max_length=254, null=True)),
                ('telefono', models.CharField(max_length=50, null=True)),
                ('bool_esta_notificada', models.BooleanField(default=False)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('edad', models.IntegerField(null=True)),
                ('bool_pauta_lista', models.BooleanField(default=False)),
                ('link_pauta_necesidades', models.URLField(null=True)),
                ('juicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='victimas', to='trial.juicio')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Testigo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('rut', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=200)),
                ('correo', models.EmailField(max_length=254, null=True)),
                ('telefono', models.CharField(max_length=50, null=True)),
                ('bool_esta_notificada', models.BooleanField(default=False)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('edad', models.IntegerField(null=True)),
                ('bool_pauta_lista', models.BooleanField(default=False)),
                ('link_pauta_necesidades', models.URLField(blank=True, null=True)),
                ('juicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testigos', to='trial.juicio')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Perito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('rut', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=200)),
                ('correo', models.EmailField(max_length=254, null=True)),
                ('telefono', models.CharField(max_length=50, null=True)),
                ('bool_esta_notificada', models.BooleanField(default=False)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('institucion', models.CharField(max_length=30)),
                ('juicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peritos', to='trial.juicio')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perfiles', to='trial.equipo')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Apoyo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('tl', 'Traslado'), ('et', 'Estadía'), ('al', 'Alimentación'), ('am', 'Asistencia Médica'), ('pe', 'Protección Especial'), ('td', 'Traductor'), ('cs', 'Consular')], max_length=2)),
                ('estado', models.CharField(choices=[('so', 'Solicitado'), ('co', 'En Coordinación'), ('ej', 'Ejecutado')], max_length=2)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('traslado_tipo', models.CharField(blank=True, choices=[('lo', 'Local'), ('or', 'Otra Región')], max_length=2, null=True)),
                ('traslado_vehiculo', models.CharField(blank=True, choices=[('tx', 'Taxi'), ('vi', 'Vehículo Institucional'), ('bs', 'Bus'), ('av', 'Avión')], max_length=2, null=True)),
                ('estadia_con_alimentacion', models.BooleanField(blank=True, default=False, null=True)),
                ('asistencia_medica_tipo', models.CharField(blank=True, choices=[('pq', 'Psiquiátrica'), ('pc', 'Psicológica'), ('ot', 'Otro')], max_length=2, null=True)),
                ('traductor_idioma', models.CharField(blank=True, max_length=20, null=True)),
                ('equipo_a_cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apoyos', to='trial.equipo')),
                ('testigo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apoyos', to='trial.testigo')),
                ('victima', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apoyos', to='trial.victima')),
            ],
        ),
    ]
