# Generated by Django 4.2.4 on 2023-08-25 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pautanecesidadestestigo',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pautanecesidadesvictima',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testigo',
            name='link_pauta_necesidades',
            field=models.URLField(blank=True, null=True),
        ),
    ]
